### ISSUE TITLE
[BUG Report] 当插件所在仓库被部署在 Netlify 上会有异常

### ISSUE THREAD

**Issue by flipwind** [dingshaohua-cn/vuepress-theme-sidebar#1]
![image](https://github.com/dingshaohua-cn/vuepress-theme-sidebar/assets/89458091/bb20e262-09c6-4362-a1eb-0c5e0f10ba27)
上面这一张图片是部署到``Netlify``时侧边栏（SideBar）的图片。

![image](https://github.com/dingshaohua-cn/vuepress-theme-sidebar/assets/89458091/1b03bc33-0e92-46f4-8c30-96cda515a007)
而这里一张图片是本地开发时侧边栏的图片。

如图所示，当我把这个项目部署到``Netlify``上的时候，会出现异常的扫盘现象，导致会把无关文件一起被拉上去，导致显示时多了一些无用文件。并且，文件夹和文件的关系无法体现，即“文件夹不显示，文件变成一级标题”的现象。

附已知情况：
```
本地配置：
Windows 10
Node Version --> v20.2.0 
npm --> v9.6.6
Vuepress Version --> v2.0.0-beta.62 

Netlify 配置：
Build image: --> Ubuntu Focal 20.04 (default)
Node Version: --> 14/16/20 都已经试过

Netlify 命令：
Build command: --> npm docs:build
Publish directory: --> docs/.vuepress/dist
```
目前情况：
构建无问题，文件夹结构的显示出问题。
各种力所能及的方法都已经试过，但是没有任何用。

我的想法：
Windows 和 Ubuntu 的开发逻辑是否不同？

**Comment by dingshaohua-com** [comment]
> ![image](https://user-images.githubusercontent.com/89458091/243169173-bb20e262-09c6-4362-a1eb-0c5e0f10ba27.png) 上面这一张图片是部署到`Netlify`时侧边栏（SideBar）的图片。
> 
> ![image](https://user-images.githubusercontent.com/89458091/243168981-1b03bc33-0e92-46f4-8c30-96cda515a007.png) 而这里一张图片是本地开发时侧边栏的图片。
> 
> 如图所示，当我把这个项目部署到`Netlify`上的时候，会出现异常的扫盘现象，导致会把无关文件一起被拉上去，导致显示时多了一些无用文件。并且，文件夹和文件的关系无法体现，即“文件夹不显示，文件变成一级标题”的现象。
> 
> 附已知情况：
> 
> ```
> 本地配置：
> Windows 10
> Node Version --> v20.2.0 
> npm --> v9.6.6
> Vuepress Version --> v2.0.0-beta.62 
> 
> Netlify 配置：
> Build image: --> Ubuntu Focal 20.04 (default)
> Node Version: --> 14/16/20 都已经试过
> 
> Netlify 命令：
> Build command: --> npm docs:build
> Publish directory: --> docs/.vuepress/dist
> ```
> 
> 目前情况： 构建无问题，文件夹结构的显示出问题。 各种力所能及的方法都已经试过，但是没有任何用。
> 
> 我的想法： Windows 和 Ubuntu 的开发逻辑是否不同？

你好 确实兼容问题。
linux和windows的路径返回格式不同导致的BUG。
现已经解决。
谢谢反馈！
