### ISSUE TITLE
vuepress@2.0.0-rc.0 版本无法安装该插件

### ISSUE THREAD

**Issue by kevinzhao2233** [dingshaohua-cn/vuepress-theme-sidebar#4]
安装后启动会报错 `no such file or directory, open 'project\node_modules\@vuepress\theme-default\lib\client\components\Page.vue'`

猜测是因为 vuepress 版本更新，导致路径有变化（不过话说官方文档里自定义主题那部分的路径引用也会报错）。

**Comment by dingshaohua-com** [comment]
可以的  我试过了
[vuepress-theme-sidebar-demo.zip](https://github.com/dingshaohua-cn/vuepress-theme-sidebar/files/13672493/vuepress-theme-sidebar-demo.zip)

**Comment by laerpeeK** [comment]
我安装你哪个demo是OK的 但我自己的项目则会报相同的错误。 对应的依赖项版本相同。 我用的包管理器是pnpm。不清楚是不是这个原因

**Comment by laerpeeK** [comment]
@dingshaohua-cn
