### ISSUE TITLE
怎么控制 左侧栏菜单的顺序，老哥！！！

### ISSUE THREAD

**Issue by evatxu** [dingshaohua-cn/vuepress-theme-sidebar#5]
怎么控制 左侧栏菜单的顺序，老哥！！

**Comment by dingshaohua-com** [comment]
排序  
还记得我们手动写的侧边栏 自己控制顺序，
但是我们这个是自动生成的，所以会根据文件名进行排序，这也是默认主题自动排序的规则
可以考虑后期加一个order或sort之类的头部元素据
来控制排序

**Comment by dingshaohua-com** [comment]
> 怎么控制 左侧栏菜单的顺序，老哥！！

要不 你要感兴趣也帮忙commit呗  我来合并

**Comment by XY0797** [comment]
> 怎么控制 左侧栏菜单的顺序，老哥！！

在[PR#9](https://github.com/dingshaohua-cn/vuepress-theme-sidebar/pull/9)中被实现，使用我实现自定义的优先级即可调整顺序，数字大的排上面
如果有不需要展示的文件(文件夹)也可以用新增的自定义隐藏属性来屏蔽掉
你的issues可以Close了

**Comment by dingshaohua-com** [comment]
> > 怎么控制 左侧栏菜单的顺序，老哥！！
> 
> 在[PR#9](https://github.com/dingshaohua-cn/vuepress-theme-sidebar/pull/9)中被实现，使用我实现自定义的优先级即可调整顺序，数字大的排上面 如果有不需要展示的文件(文件夹)也可以用新增的自定义隐藏属性来屏蔽掉 你的issues可以Close了
